server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/credit_platform
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:53649713}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Ollama settings
ollama.api.url=http://localhost:11434/api/generate
