server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/credit_platform
spring.datasource.username=postgres
spring.datasource.password=53649713
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Ollama settings
ollama.api.url=http://localhost:11434/api/generate